name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 배포 성공
        if: success()
        run: echo "배포 완료!"

      - name: 배포 실패
        if: failure()
        run: echo "배포 실패! 로그를 확인하세요."

      - name: 명령어 여러개 한번에 사용할 경우
        run: |
          echo "Hellow"
          echo "World"

      - name: EC2 접속
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }} # → 13.124.215.243
          username: ${{ secrets.EC2_USERNAME }} # → ubuntu
          key: ${{ secrets.EC2_KEY }} # → pem 내용

          script: | # 실제 코드 수정하는 부분
            cd ~/board-app-github-actions-v1
            docker compose pull
            docker compose up -d
            docker image prune -f

#######################################################
##########  이건 보험임. 일단 안해도 됨 #############
#script: |    # 실제 코드 수정하는 부분
#cd ~/board-app-github-actions-v1
#git pull origin main
#docker compose down
#docker compose build --no-cache
#docker compose up -d
#docker image prune -f
